name: "Deploy to EKS"
on:
  push:
    branches: [main,thisisommore/use-public-image-50]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    env:
     NEXT_PUBLIC_MARKETPLACE_ADDRESS: ${{ secrets.NEXT_PUBLIC_MARKETPLACE_ADDRESS }}
     NEXT_PUBLIC_CREATIFY_ADDRESS: ${{ secrets.NEXT_PUBLIC_CREATIFY_ADDRESS }}
     NEXT_PUBLIC_GRAPHQL_API: ${{ secrets.NEXT_PUBLIC_GRAPHQL_API }}
     NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
     ENV_FILE: ${{ secrets.ENV_FILE }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: "public"

      - name: Skaffold build and deploy
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          echo "$ENV_FILE" | base64 -d > .env
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/v1.23.6/bin/linux/amd64/kubectl.sha256"
          echo "$(<kubectl.sha256)  kubectl" | sha256sum --check
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG_DATA" | base64 -d > ~/.kube/config
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
          skaffold run
